/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme.ts
 * Command: astryx theme build theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/// <reference path="./nymspace.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const nymspaceTheme: DefinedTheme;
