/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme.ts
 * Command: astryx theme build theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface HeadingTypeMap {
    'display-1': true;
    'display-2': true;
    'display-3': true;
  }
}
